ovsdb: Fix -Wimplicit-int-float-conversion warning
This patch fixes the -Wimplicit-int-float-conversion report
by clang, and thus resolves the breakage of BSD build by
cirrus-ci. From:

https://cirrus-ci.com/task/5928699675541504?command=build#L1652

ovsdb/execution.c:733:32: error: implicit conversion from
'long long' to 'double' changes value from 9223372036854775807
to 9223372036854775808 [-Werror,-Wimplicit-int-float-conversion]
            timeout_msec = MIN(LLONG_MAX, json_real(timeout));
                           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/limits.h:69:19: note: expanded from macro 'LLONG_MAX'
                        ^~~~~~~~~~~
/usr/include/x86/_limits.h:74:21: note: expanded from macro '__LLONG_MAX'

Signed-off-by: Yi-Hung Wei <yihung.wei@gmail.com>